//FETCH CONTROLLERS
// export const FETCHING_DATA = "FETCHING_DATA";
// export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
// export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

export const TODOLIST_CREATE = "TODOLIST_CREATE";
export const TODOLIST_DELETE = "TODOLIST_DELETE";
export const TODOLIST_CHECK = "TODOLIST_CHECK";
export const TODOLIST_GET_ID = "TODOLIST_GET_ID";


export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const OPEN_MODAL_OPTION = "OPEN_MODAL_OPTION";
export const CLOSE_MODAL_OPTION = "CLOSE_MODAL_OPTION";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const CLOSE_MODAL_SESION = "CLOSE_MODAL_SESION";
export const OPEN_MODAL_SESION = "OPEN_MODAL_SESION";